$(document).ready(function(){
    $('.cardContainer').cardcontainer({
        auto:true,
        speed:500,
        pause:5000,
        mode:'horizontal',
        autoControls:true,
        pager:true,
        captions:true,
    });
})